# -*- coding: utf-8 -*-
# Vollständige Moduldaten Modulverzeichnis v2 – Quelle: Modulhandbuch B.A. Soziale
# Arbeit, EH Ludwigsburg, Stand 03/2026

STUDIENBEREICHE = {
    1: dict(name="Grundlagen der Sozialen Arbeit als Disziplin und Profession",
            bg="#E8F5ED", tx="#1A5C34", bd="#A8D5B5", dot="#2E8B57"),
    2: dict(name="Zielgruppen und Arbeitsfelder der Sozialen Arbeit",
            bg="#EDE8FF", tx="#3B1D8C", bd="#B8A8F0", dot="#5B3FC8"),
    3: dict(name="Gesellschaftliche Rahmenbedingungen",
            bg="#E0F4EF", tx="#0D5A4A", bd="#8DD4C2", dot="#1A8C70"),
    4: dict(name="Bezugsdisziplinen",
            bg="#FEF3E2", tx="#7A5500", bd="#F5CC80", dot="#C48A00"),
    5: dict(name="Schlüsselqualifikationen",
            bg="#E0EEFF", tx="#1A3A8C", bd="#A0BCEA", dot="#2050C8"),
    6: dict(name="Sozialarbeiterische Handlungskompetenzen",
            bg="#FCE9E0", tx="#8A4526", bd="#EFC0A8", dot="#CC6B3F"),
    7: dict(name="Reflexion und Evaluation der Sozialen Arbeit",
            bg="#FCE8EF", tx="#7A1038", bd="#F0A0BC", dot="#C41A50"),
    0: dict(name="Ohne spezifische Zuordnung",
            bg="#EEEEEC", tx="#444440", bd="#BBBBBA", dot="#777775"),
}

MODULES = [
  dict(nr=1, name="Wissenschaftliches Arbeiten", sem=[1], cp=6, sws=4, sb=5,
       verantwortung="Prof. Dr. Heike Stammer",
       email="h.stammer@eh-ludwigsburg.de",
       bausteine=[("Einführung in das Wissenschaftliche Arbeiten","Seminar","UPL")],
       pruefung=("0745","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 01","BA DW 01","BA RPGP 01"]),
  dict(nr=2, name="Theorie und Methoden der Beratung in der Sozialen Arbeit", sem=[1,2], cp=6, sws=4, sb=5,
       verantwortung="Prof. Dr. Eva Maria Lohner",
       email="e.lohner@eh-ludwigsburg.de",
       bausteine=[("Einführung in die Grundlagen der psychosozialen Beratung","Vorlesung","UPL"),
                  ("Gesprächsführung und Kommunikationskompetenzen","Übung",None)],
       pruefung=("0746","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 02","BA DW 02","BA RPGP 02"]),
  dict(nr=3, name="Ethische und theologische Perspektiven", sem=[1], cp=6, sws=4, sb=1,
       verantwortung="Prof. Dr. Björn Görder",
       email="b.goerder@eh-ludwigsburg.de",
       bausteine=[("Grundlagen einer Ethik Sozialer Arbeit","Seminar","PL"),
                  ("Ethische Konflikte und ethische Urteilsbildung","Übung",None)],
       pruefung=("0747","Klausur / Referat","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 03"]),
  dict(nr=4, name="Genderperspektiven", sem=[1], cp=6, sws=4, sb=5,
       verantwortung="Prof. Dr. Johanna Possinger",
       email="j.possinger@eh-ludwigsburg.de",
       bausteine=[("Wie lese ich Daten sozialer Ungleichheit?","Vorlesung",None),
                  ("Wahlpflichtseminar zu aktuellen Themen","Seminar","PL")],
       pruefung=("0750","Hausarbeit / Referat","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 04"]),
  dict(nr=5, name="Einführung in die Soziale Arbeit als Disziplin und Profession", sem=[1], cp=6, sws=6, sb=1,
       verantwortung="Prof. Dr. Rolf Ahlrichs",
       email="r.ahlrichs@eh-ludwigsburg.de",
       bausteine=[("Einführung in die Grundfragen und Grundlagen Sozialer Arbeit","Seminar","UPL"),
                  ("Einführung in die politischen Bezüge Sozialer Arbeit","Seminar",None),
                  ("Einführung in die rechtlichen Bezüge Sozialer Arbeit","Seminar",None)],
       pruefung=("0752","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=63, selbst=117, praxis=0),
       verwendbarkeit=["BA ISA 05","BA DW 05"]),
  dict(nr=6, name="Inklusion und Exklusion", sem=[2], cp=6, sws=4, sb=3,
       verantwortung="Prof. Dr. Philine Zölls-Kaser",
       email="p.zoells-kaser@eh-ludwigsburg.de",
       bausteine=[("Inklusion – Exklusion im Kontext der Systemtheorie, Inklusionspädagogik und Theorien der Sozialen Arbeit","Vorlesung",None),
                  ("Wahlpflichtseminare","Seminar","PL")],
       pruefung=("0756","Hausarbeit / Referat","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 06","BA DW 20","BA IPHP 09"]),
  dict(nr=7, name="Entwicklung und Sozialisation", sem=[2], cp=6, sws=4, sb=4,
       verantwortung="Prof. Dr. Heike Stammer",
       email="h.stammer@eh-ludwigsburg.de",
       bausteine=[("Entwicklungs- und Sozialisationstheorien unter Berücksichtigung von Verhaltensauffälligkeiten","Vorlesung","UPL"),
                  ("Wahlpflichtseminare","Seminar",None)],
       pruefung=("0757","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 07","BA DW 07"]),
  dict(nr=8, name="Rechtliche Grundlagen und Aufträge Sozialer Arbeit", sem=[2], cp=6, sws=5, sb=4,
       verantwortung="Prof. Dr. Marc Sieper",
       email="m.sieper@eh-ludwigsburg.de",
       bausteine=[("Grundlagen des Kinder- und Jugendhilfe- sowie Familienrechts","Seminar","PL"),
                  ("Rechtliche Grundlagen und Einführung in das Grundsicherungsrecht","Seminar","PL"),
                  ("Sozialverwaltungsrecht","Seminar","PL"),
                  ("Arbeitsfelder und Aufträge Sozialer Arbeit","Seminar",None)],
       pruefung=("0759","Klausur","benotet"), voraus=[5],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 08","BA DW 08","BA RPGP 13"]),
  dict(nr=9, name="Ästhetik, Kultur, Medien", sem=[1,2], cp=6, sws=5, sb=5,
       verantwortung="Prof. Dr. Corinna Schubert",
       email="c.schubert@eh-ludwigsburg.de",
       bausteine=[("Theoretische Grundlagen (1. Sem.)","Seminar",None),
                  ("Workshop (1. Sem.)","Workshop",None),
                  ("Methodikworkshop (2. Sem.)","Workshop","PL")],
       pruefung=("0760","MtA","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 09","BA DW 09","BA RPGP 07"]),
  dict(nr=10, name="Forschung", sem=[2], cp=6, sws=5, sb=7,
       verantwortung="Prof. Dr. Peter Höfflin",
       email="p.hoefflin@eh-ludwigsburg.de",
       bausteine=[("Methoden der empirischen Sozialforschung","Vorlesung",None),
                  ("Der Einsatz von Forschungsmethoden in sozialen Arbeitsfeldern","Seminar","PL")],
       pruefung=("0764","MtA","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 10","BA DW 10"]),
  dict(nr=11, name="Projektstudium I", sem=[3], cp=12, sws=6, sb=2,
       verantwortung="Prof. Dr. Johanna Possinger / Prof. Dr. Stephanie Goeke",
       email="j.possinger@eh-ludwigsburg.de / s.goeke@eh-ludwigsburg.de",
       bausteine=[("Projekt","Praxis",None),
                  ("Projektbegleitseminar (PBS)","Seminar","PL"),
                  ("Theorie- / Praxisbezug","Seminar",None),
                  ("Präsentationstag inkl. Vorbereitung","Workshop",None)],
       pruefung=("0766","MtA","benotet"), voraus=[1,4,5,8,10],
       workload=dict(gesamt=360, kontakt=63, selbst=147, praxis=150),
       verwendbarkeit=["BA ISA 11","BA DW 11"]),
  dict(nr=12, name="Unterstützung bei der Lebensbewältigung: Beratung und Begleitung", sem=[3], cp=6, sws=4, sb=6,
       verantwortung="Prof. Dr. Eva Maria Lohner",
       email="e.lohner@eh-ludwigsburg.de",
       bausteine=[("Methoden zur Beratung Einzelner, von Familien und Gruppen","Seminar","UPL"),
                  ("Professionelle Anforderungen in den Feldern der Sozialen Arbeit","Übung",None)],
       pruefung=("0770","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 12","BA DW 12","BA RPGP 20"]),
  dict(nr=13, name="Rechtliche Perspektiven und Organisationsgrundlagen Sozialer Arbeit", sem=[3], cp=6, sws=4, sb=2,
       verantwortung="Prof. Dr. Tamara Bloch",
       email="t.bloch@eh-ludwigsburg.de",
       bausteine=[("Vertiefung des Grundsicherungs- und Sozialhilferechts","Seminar","PL"),
                  ("Vertiefung des Kinder- und Jugendhilfe- sowie Familienrechts / Prävention sexualisierter Gewalt","Seminar","PL"),
                  ("Organisationsgrundlagen","Seminar",None)],
       pruefung=("0771","Klausur","benotet"), voraus=[8],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 13","BA DW 18"]),
  dict(nr=14, name="Internationale, interkulturelle und interreligiöse Perspektiven", sem=[3], cp=6, sws=5, sb=5,
       verantwortung="Prof. Dr. Nadine Sylla",
       email="n.sylla@eh-ludwigsburg.de",
       bausteine=[("Vielfalt und Unterschiedlichkeit in der Migrationsgesellschaft","Vorlesung",None),
                  ("Wahlpflichtseminare","Seminar","PL"),
                  ("Interkulturelles und diversityorientiertes Training","Workshop",None)],
       pruefung=("0772","Referat / Hausarbeit","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 14","BA DW 14"]),
  dict(nr=15, name="Projektstudium II", sem=[4], cp=12, sws=6, sb=6,
       verantwortung="Prof. Dr. Johanna Possinger / Prof. Dr. Stephanie Goeke",
       email="j.possinger@eh-ludwigsburg.de / s.goeke@eh-ludwigsburg.de",
       bausteine=[("Projekt","Praxis",None),
                  ("Projektbegleitseminar (PBS)","Seminar","PL"),
                  ("Theorie- / Praxisbezug","Seminar",None),
                  ("Präsentationstag inkl. Vorbereitung","Workshop",None)],
       pruefung=("0774","MtA","benotet"), voraus=[1,4,5,8,10],
       workload=dict(gesamt=360, kontakt=63, selbst=147, praxis=150),
       verwendbarkeit=["BA ISA 15","BA DW 15","BA RPGP 15"]),
  dict(nr=16, name="Kasuistik, Case-Management und Hilfeplanung", sem=[4], cp=6, sws=5, sb=6,
       verantwortung="Prof. Dr. Elke Schierer",
       email="e.schierer@eh-ludwigsburg.de",
       bausteine=[("Einführung in das theoriegeleitete, methodische Handeln / Case-Management","Seminar","PL"),
                  ("Anwendungsformen in Arbeitsbereichen, Hilfeplanung","Übung",None)],
       pruefung=("0778","mündliche Prüfung","benotet"), voraus=[2,5,8,12],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 16","BA DW 16"]),
  dict(nr=17, name="Unterstützung ausgewählter Zielgruppen in Rechtsfragen und betriebswirtschaftliche Aspekte", sem=[4], cp=6, sws=4, sb=4,
       verantwortung="Prof. Dr. Annette Rabe",
       email="a.rabe@eh-ludwigsburg.de",
       bausteine=[("Wahlpflichtseminare","Seminar","UPL"),
                  ("Betriebswirtschaftliche Aspekte","Seminar","UPL")],
       pruefung=("0779","MtA","unbenotet"), voraus=[8],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 17"]),
  dict(nr=18, name="Gesellschaftliche Strukturen und Prozesse", sem=[4], cp=6, sws=5, sb=3,
       verantwortung="Prof. Dr. Peter Höfflin",
       email="p.hoefflin@eh-ludwigsburg.de",
       bausteine=[("Einführung in grundlegende allgemeine Theorien und Schlüsselbegriffe der Soziologie","Vorlesung",None),
                  ("Soziologische Grundlagen in speziellen Arbeitsfeldern","Seminar","PL")],
       pruefung=("0781","Hausarbeit / Referat","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 18","BA DW 24"]),
  dict(nr=19, name="Praxissemester", sem=[5], cp=30, sws=3, sb=6,
       verantwortung="Beatrice Gerst",
       email="b.gerst@eh-ludwigsburg.de",
       bausteine=[("Praxispräsenzzeit","Praxis (800 h)",None),
                  ("Praxisbegleitende Lehrveranstaltung (PBL)","Seminar","UPL"),
                  ("Reflexionszeit zur Selbstevaluation / Dokumentationszeit","Selbststudium (68 h)",None)],
       pruefung=("0783","MtA","unbenotet"), voraus=["Module 01–18 (gesamter 1. Studienabschnitt)"],
       workload=dict(gesamt=900, kontakt=32, selbst=68, praxis=800),
       verwendbarkeit=["BA ISA 19","BA DW 19","BA RPGP 19"]),
  dict(nr=20, name="Rahmenbedingungen Sozialer Arbeit und Öffentlichkeitsbezug", sem=[6], cp=6, sws=4, sb=6,
       verantwortung="Prof. Dr. Jens Müller",
       email="j.mueller@eh-ludwigsburg.de",
       bausteine=[("Moderation und Kommunikation","Seminar","PL"),
                  ("Marketing und Fundraising","Übung",None)],
       pruefung=("0784","Hausarbeit / Referat","benotet"), voraus=[13,17],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 20"]),
  dict(nr=21, name="Soziale Arbeit als Disziplin und Profession", sem=[6], cp=6, sws=6, sb=7,
       verantwortung="Prof. Dr. Elke Schierer",
       email="e.schierer@eh-ludwigsburg.de",
       bausteine=[("Theorien Sozialer Arbeit, disziplinäre Grundlagen und ihre Relevanz für methodische Konzepte und Handlungsherausforderungen","Seminar","PL"),
                  ("Biografisch orientierte Kompetenzprofilierung / Projekt BA-Thesis","Seminar",None)],
       pruefung=("0787","MtA","benotet"), voraus=[5,19],
       workload=dict(gesamt=180, kontakt=63, selbst=117, praxis=0),
       verwendbarkeit=["BA ISA 21","BA DW 21"], modulart="Wahlpflichtmodul"),
  dict(nr=22, name="Gemeinwesen und Sozialraum in pluralen Gesellschaften", sem=[6], cp=6, sws=5, sb=2,
       verantwortung="Prof. Dr. Nadine Sylla",
       email="n.sylla@eh-ludwigsburg.de",
       bausteine=[("Von der Gemeinwesenarbeit über das Quartiersmanagement zur Sozialraumorientierung und zurück?","Vorlesung",None),
                  ("Wahlpflichtseminare","Seminar","PL"),
                  ("Das Allgemeine Gleichbehandlungsgesetz (AGG)","Seminar",None),
                  ("Methoden der Gemeinwesenarbeit und der Sozialraumanalyse","Workshop",None)],
       pruefung=("0789","Referat / Hausarbeit","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=53, selbst=127, praxis=0),
       verwendbarkeit=["BA ISA 22","BA DW 22","BA RPGP 25"]),
  dict(nr=23, name="Diakonie und weltanschauliche Organisationen im sozialen Wandel: religiöse und ethische Perspektiven", sem=[6], cp=6, sws=4, sb=4,
       verantwortung="Prof. Dr. Björn Görder",
       email="b.goerder@eh-ludwigsburg.de",
       bausteine=[("Wertebasiertes soziales Handeln im Kontext von Sozialstaat, Subsidiarität und Freier Wohlfahrtspflege","Vorlesung",None),
                  ("Diakonische und ethische Fragestellungen in Organisationen der Sozialwirtschaft","Seminar","PL")],
       pruefung=("0794","MtA","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 23","BA DW 23"]),
  dict(nr=24, name="Gesundheit und Soziale Arbeit / Gesundheitsförderung", sem=[6], cp=6, sws=4, sb=4,
       verantwortung="Prof. Dr. Simone Ries",
       email="s.ries@eh-ludwigsburg.de",
       bausteine=[("Einführung in Theorie und Praxis der gesundheitsbezogenen Sozialen Arbeit","Vorlesung","UPL"),
                  ("Wahlpflichtseminare","Seminar",None)],
       pruefung=("0796","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 24"]),
  dict(nr=25, name="Organisation und Management sozialer Einrichtungen", sem=[7], cp=6, sws=4, sb=6,
       verantwortung="Prof. Dr. Jens Müller",
       email="j.mueller@eh-ludwigsburg.de",
       bausteine=[("Sozialmanagement","Seminar","PL"),
                  ("Arbeitsrecht","Seminar",None)],
       pruefung=("0799","Klausur","benotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 25","BA RPGP 21"]),
  dict(nr=26, name="Gestaltung von Lern- und Bildungsprozessen", sem=[7], cp=6, sws=4, sb=4,
       verantwortung="Prof. Dr. Elke Reichmann",
       email="e.reichmann@eh-ludwigsburg.de",
       bausteine=[("Erziehungswissenschaftliche Grundlagen von Lern- und Bildungsprozessen","Vorlesung","UPL"),
                  ("Wahlpflichtseminare","Seminar",None)],
       pruefung=("0802","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 26"]),
  dict(nr=27, name="Sozialpolitik und transnationale Bezüge Sozialer Arbeit", sem=[7], cp=6, sws=4, sb=3,
       verantwortung="Prof. Bettina Heinrich",
       email="b.heinrich@eh-ludwigsburg.de",
       bausteine=[("Allgemeine politische, volkswirtschaftliche und geopolitische Rahmenbedingungen Sozialer Arbeit","Seminar","UPL"),
                  ("Politische Handlungsfelder Sozialer Arbeit","Seminar","UPL")],
       pruefung=("0803","MtA","unbenotet"), voraus=[],
       workload=dict(gesamt=180, kontakt=42, selbst=138, praxis=0),
       verwendbarkeit=["BA ISA 27"]),
  dict(nr=28, name="Bachelor-Thesis / Bachelor-Kolloquium", sem=[7], cp=12, sws=0, sb=0,
       verantwortung="Studiengangsleitung",
       email="r.ahlrichs@eh-ludwigsburg.de",
       bausteine=[("Bachelor-Thesis","Thesis",None),
                  ("Bachelor-Kolloquium","Kolloquium",None)],
       pruefung=("8900 / 8905","Thesis + Kolloquium","benotet"),
       voraus=["Bestehen des Praxissemesters (Modul 19)"],
       workload=dict(gesamt=360, kontakt=0, selbst=360, praxis=0),
       verwendbarkeit=[]),
]
